sonar:
  ports:
   - "9000:9000"
  labels:
    io.rancher.sidekicks: plugins
  image: sonarqube
  links:
   - db:dbsonar
  environment:
   - SONARQUBE_JDBC_URL=jdbc:postgresql://dbsonar:5432/sonar
  volumes_from:
  - plugins
plugins:
  labels:
    io.rancher.container.start_once: 'true'
  image: sonarqube
  volumes:
   - /opt/sonarqube/extensions
   - /opt/sonarqube/lib/bundled-plugins
  command: /bin/true


db:
  labels:
    io.rancher.sidekicks: datadb
  image: postgres
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar
  volumes_from:
    - datadb

datadb:
  labels:
    io.rancher.container.start_once: 'true'
  image: postgres
  volumes:
    - /var/lib/postgresql
  command: /bin/true

