master:
  ports:
  - 8090:8080/tcp
  environment:
    '# JENKINS_CERTIFICATE_DNAME': CN=SBleul,OU=Blacklabelops,O=blacklabelops.com,L=Munich,S=Bavaria,C=D
    '# JENKINS_KEYSTORE_PASSWORD': swordfish
    JAVA_VM_PARAMETERS: -Xmx1024m -Xms512m
    JENKINS_MASTER_EXECUTORS: '0'
    JENKINS_PLUGINS: swarm
    JENKINS_SLAVEPORT: '50000'
  external_links:
  - vol1/jenkinslogs:jenkinsdata
  - vol1/jenkinsdata:jenkinsdata
  labels:
    com.blacklabelops.description: Jenkins Continuous Integration System
    com.blacklabelops.service: jenkins-master
    io.rancher.container.dns: true
  tty: true
  image: blacklabelops/jenkins:alpine
  net: host
slave:
  labels:
    com.blacklabelops.applications: java maven gradle
    com.blacklabelops.description: Jenkins Swarm JDK-8 Slave
    com.blacklabelops.service: slave
  image: blacklabelops/swarm-jdk8
  net: host
