sonar:
  ports:
  - 9000:9000/tcp
  environment:
    SONARQUBE_JDBC_URL: jdbc:postgresql://dbsonar:5432/sonar
  external_links:
  - vol/plugins:plugins
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.dns: 'true'
  tty: true
  image: sonarqube
  links:
  - db:dbsonar
  privileged: true
  stdin_open: true
  net: host
db:
  environment:
    POSTGRES_PASSWORD: sonar
    POSTGRES_USER: sonar
  external_links:
  - vol/datadb:datadb
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.dns: 'true'
  tty: true
  image: postgres
  privileged: true
  stdin_open: true
  net: host
